apiVersion: v1
kind: Pod
metadata:
  name: badcontainer
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
spec:
  containers:
  - name: badcontainer
    image: 192.168.111.50:5000/alpine-containertools
